using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace DevExpress
{
    public partial class Form2 : Form
    {
        public Form2()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            kullanıcı_GirisTableAdapter1.Fill(kutuphaneDataSet1.Kullanıcı_Giris);
        }

        private void pivotGridControl1_Click(object sender, EventArgs e)
        {

        }
    }
}
